services:
  frontend:
    build:
      context: ./problem-solver-fe
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ./problem-solver-be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=username
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=problem_solver
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: problem_solver
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

volumes:
  pgdata:

networks:
  default:
    driver: bridge